# Generated by Django 3.0.4 on 2020-03-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('date_de_naissance', models.DateField(verbose_name='Date de naissance')),
                ('fonction', models.CharField(max_length=100)),
                ('photo_de_profil', models.ImageField(upload_to='uploads/', verbose_name='Photo de profil')),
            ],
        ),
    ]
